### ISSUE TITLE
Number of elections in the study period

### ISSUE THREAD

**Issue by mberneaud** [mberneaud/DataScienceAssignment2#1]
Dear Jonas, 
do you happen to have the number of municipal elections in Bavaria in our study period handy somewhere? I think they would be a good addition for the description of the data / reiteration thereof in the conclusion.

**Comment by jmarkgraf** [comment]
6,267 elections between 2000-14

**Comment by jmarkgraf** [comment]
Not sure if we need to describe the data already though. I deleted all descr statistics for the moment.

**Comment by mberneaud** [comment]
I think it's not absolutely crucial but it helps given that you already describe the number of municipalities and _Sparkassen_. I just added this little statistic and pushed it to the repo.
