### ISSUE TITLE
Interaction in model? 

### ISSUE THREAD

**Issue by mberneaud** [mberneaud/DataScienceAssignment2#2]
I wrote down my ideas for the statistical model, but I was unsure whether you intended to model board membership as an intervening variable in between the incumbency advantage and re-election in terms of a mathematical interaction, so I left it out. From my perspective, it does not really seem necessary if we model re-election/ non-re-election as a binary dependent variable to which we apply a logit model. Then, we could just include board membership into the model as a regular IV and see how it changes the chance of re-election. 

Please feel free to correct me and add an interaction to the model in case I misunderstood your conference paper.

**Comment by jmarkgraf** [comment]
No, I don't think we need interactions, at least not at this point. Potentially it would make sense to include them as controls later, but this is rather sth we can check once we have the data cleaned and model the relationship. Interactions are not needed for the IV as we compare mayors with and without board seat. Eventually we might want to control for confounding factors with interactions (e.g. board membership and municipality size / fiscal situation in municipality) though.
