### ISSUE TITLE
Edits on Statistical Model

### ISSUE THREAD

**Issue by jmarkgraf** [mberneaud/DataScienceAssignment2#4]
Hi Malte,

Thanks for your contributions on the statistical model. I think it nicely summarizes the estimation strategy.
I did a few edits though as I'm not sure if we can meet the high expectations that we raise by announcing to control for board competence as well as fiscal situation in the municipality. You correctly point to the controls that Guillermo and I might use in the paper, but we don't have sufficient data to model those controls at this point. Board competency measures would require us to go through all job descriptions of mayors and develop a taxonomy for them. Moreover, I haven't collected data on municipal fiscal indicators yet; would be great if we would manage to do that in the course of the assignments though.
I hope that's all fine for you!

**Comment by mberneaud** [comment]
Alright, then we have to tone down our expectations a bit and see where we can find data on municipal fiscal indicators of some sort.

**Comment by jmarkgraf** [comment]
Merci! Could you have a final look at the paper? I will do so, too. Its almost exactly 2000 words now and I think we cover most parts!

**Comment by mberneaud** [comment]
Did you make any further changes? In that case could you push them to the repo please so I could have a look?

**Comment by jmarkgraf** [comment]
No, I have pushed all my changes already.

**Comment by mberneaud** [comment]
Could you try and re-sync them again as the last commit on this repo here was made by me, 21h ago.

**Comment by jmarkgraf** [comment]
This is very well possible. I didn't make any changes. I would just like to make sure that we have corrected all typos and other formalities. Once we have checked for that, I would say we can send it off. I will go through it one last time later this afternoon, too.

**Comment by mberneaud** [comment]
Just finished my proof-reading and pushed my changes to the repo.

**Comment by jmarkgraf** [comment]
Perfect! Thanks. I gonna do the same and send the link to Christopher then! Enjoy your Easter "break"!

**Comment by mberneaud** [comment]
Great! Enjoy yours also. Since this "issue" is done with, I'll close it.
